#!/usr/bin/env python3

import sys
def get_channel_id(paddr):
    addr = paddr & 0xFFFFFFFF80
    bit0 = 0
    bit1 = 0
    while addr != 0:
        bit0 = bit0 ^ (addr & 1)
        addr = addr >> 1
        bit1 = bit1 ^ (addr & 1)
        addr = addr >> 1
    return ((bit1 << 1) | bit0)

print(get_channel_id(int(sys.argv[1], 16)))
